### ISSUE TITLE
Update dm (utils, errors, model) and fully document

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/VDM#185]
__Background__: behind VDM and MVDM is a "DM" model that supports Create-Update-Remove-Delete as well as Retrieval. It also supports delegation of implementation to FileMan (form of dependent and may merge).

__Formalizes and Extends the FM/DD/VDM pattern__

__End Requirement__: need WP/wiki specifying this model

- [ ] nix TODOs in dmUtils (bring in here)
- [ ] Symbol etc for Errors
- [ ] dmUtils expand to cover remove/delete permission (as operations vs parameter-centric) ie/ a prepare for delete, prepare for remove. Also update (if no updatable => OPERATION NOT PERMITTED ERROR)

Particulars of DM include:
  * wp strings
  * remove/unremove vs delete
  * computed/dependent including FM vs VDM computed
  * portable ids vs local (and many ids) ... namespace support
  * proxy ids (ex/ facility etc for IHS)
  * objects have meaningful names (labels) ... MVDM generated but VDM as .01 or layered on
  * describe returns structure for dates/ids

... remove/unremove and nuance for update are key for __document generated for MVDM__

Errors so far ...

```text
const DMERRORS = {

    ID_NOT_PERMITTED: 1,
    IEN_NOT_PERMITTED: 2,
    ID_REQUIRED: 10,
    ID_INVALID: 11,
    IEN_REQUIRED: 12, <-------- need to formalize IEN vs ID
    OBJECT_ALREADY_EXISTS: 9, // uniqueness/keys

    CLASS_ERROR: 10, // CLASS SPECIFIC ERROR (not caught here but from validator)

    PROPERTIES_INVALID_FOR_CREATE: 3,
    PROPERTIES_INVALID_FOR_UPDATE: 3,
    PROPERTIES_DEPRECATED: 4,
    PROPERTIES_REQUIRED_ABSENT: 5,
    PROPERTIES_FM_MANAGED: 6, // as functionality delegated to FileMan (form of dependent ... merge it?)
    PROPERTIES_DEPENDENT: 7, <--- rename as "COMPUTED"?
    PROPERTY_VALUES_INVALID: 8
} 
```

__NEED GREATLY EXPANDED -spec for all nuances__

## Absent seem to be:

  * DELETE_NOT_SUPPORTED
  * REMOVE_NOT_SUPPORTED
  * UPDATE_NOT_SUPPORTED
  * UNREMOVE_NOT_SUPPORTED

## Class specific errors - validators - how to name/propogate these sub errors

Need to also fit these errors in with domain object specific errors ie/ transaction level errors (or are they handled by "validators".) Do such things as secondary errors ie/ CLASS_SPECIFIC_ERROR and then it's error id.

## Proxy Ids

```text
    function facilityToUse(facilityId, propInfo) {
        if (propInfo.hasOwnProperty("range") && /\-/.test(propInfo.range.id)) {
            let fmTypeId = propInfo.range.id.split("-")[1];
            return fmTypeId + "-" + facilityId.split("-")[1];
        }
        return facilityId;
    }
```

## Templates

Consider $USERID etc in consts or an enum ie/ as SYMBOLS.

## Overchecking in dmUtils vs consistency check on DM statically

>     /* **** IMPORTANT TODO: some of the following checks (deprecated/fmManaged/dependent) shouldn't arise as create shouldn't be true. This should be checked in a DM checker and not here */

right now checking if dep being set as create property when should set directly.

## Efficiency/FMQL

Hiding DESCRIBE checks/uniqueness etc here and FMQL query invocation. Need to formalize that syntax.

## Nuance for values

  * WP string check ... should get own error? as Long String/WP string is special?
  * label for object/reference support ie/ generating meaningful labels for all MVDM anyhow
  * portable ids/vuid formal support

## TODO OTHERS:
  * Javascripts Class/immutable etc
  * Mongoose if any
 
## Property paths - more on this

```text
{ valid: false,
  error: 14,
  properties: [ 'property4[0]/mproperty1' ] }
```

**Comment by conorcaregraf** [comment]
## MVDM JS Class Generator

Consider static generator for MVDM ie/ off a DMClass base, add constructor for required and allow others and default can't remove or unremove or ...
